### ISSUE TITLE
vsrepo update fails with 406 error

### ISSUE THREAD

**Issue by nergdron** [vapoursynth/vsrepo#150]
I just installed vapoursynth on a machine yesterday, but `vsrepo.py update` is failing for me with a 406 error:

```
>vsrepo update
Traceback (most recent call last):
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 916, in <module>
    update_package_definition('http://www.vapoursynth.com/vsrepo/vspackages3.zip')
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 720, in update_package_definition
    with urllib.request.urlopen(req_obj) as urlreq:
  File "C:\Program Files\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 406: Not Acceptable
```

I found the URL for the file in the source, and when I manually download that with firefox or similar, it works fine. But vsrepo just refuses to download it.

**Comment by theChaosCoder** [comment]
Same here.
@myrsloik I reuploaded the file but the error is still there. Seems like something on the server side changed.

**Comment by myrsloik** [comment]
Fixed, apparently my host changed the web server to reject all requests without a user agent. Fixed now.

**Comment by nergdron** [comment]
hmmm I'm still getting a 406 from here. are you sure it's fixed? 😅

**Comment by theChaosCoder** [comment]
You need to download vsrepo.py and replace it manually.

**Comment by nergdron** [comment]
ahh gotcha, thanks.
